In [2]:
import tensorflow as tf

#Initializing tensors
#tf.constant(value,shape,dtype) | shape=size of the tensor
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
x = tf.constant([[1,2,3],[4,5,6]])
x = tf.ones((3,3))
x = tf.eye(3) #Identity matrix of shape 3x3

In [ ]:
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [12]:
#Methods to generate random values
#uniform method generates random values from range(minval,maxval) , maxval is excluded.all values are equally likely.
y=tf.random.uniform((2,3), minval=10,maxval=50,dtype=tf.int32)
print(f"y={y}")

#normal method generates random values based on the principle of Gaussian curve. Probability of values near the mean is high.Standard deviation tells how spread out will be the range from the mean.
#smaller the stddev, narrower is the curve and vice versa.
z=tf.random.normal(shape=(2,3), mean=5.0, stddev=10.0)
print(f"z={z}")

y=[[20 14 30]
 [17 42 44]]
z=[[  9.657778    22.931452     3.729022  ]
 [ -0.37139416 -15.557394    15.600655  ]]


In [23]:
#range() generates values from start=n to limit=n_final. Values will be from n to n_final-1. delta parameter determines the size of step.
p=tf.range(dtype=tf.float32,start=5,limit=21,delta=2)
print(f"p={p}")
q=tf.range(start=5,limit=21,delta=1,dtype=tf.int32)
print(f"q={q}")

p=[ 5.  7.  9. 11. 13. 15. 17. 19.]
q=[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [31]:
#type casting
print(tf.cast(q,tf.float32))


tf.Tensor([ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.], shape=(16,), dtype=float32)


In [32]:
#Mathematical operations
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
print(tf.add(x,y))
      #OR
print(f"x+y={x+y}")
print(f"x-y={x-y}")
print(f"x*y={x*y}")
print(f"x/y={x/y}")
print(f"x^2={x**2}")

A=tf.random.uniform((3,2))
B=tf.random.uniform((2,3))
print(tf.matmul(A,B))
print(A @ B)


tf.Tensor([10 10 10], shape=(3,), dtype=int32)
x+y=[10 10 10]
x-y=[-8 -6 -4]
x*y=[ 9 16 21]
x/y=[0.11111111 0.25       0.42857143]
x^2=[1 4 9]
tf.Tensor(
[[1.0070174  1.0615395  0.4164695 ]
 [0.86202    0.8909278  0.30765104]
 [0.78697765 0.8412951  0.35766828]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1.0070174  1.0615395  0.4164695 ]
 [0.86202    0.8909278  0.30765104]
 [0.78697765 0.8412951  0.35766828]], shape=(3, 3), dtype=float32)


In [48]:
#indexing
x=tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::3])
print(x[::-1])

A=tf.random.uniform((3,3),minval=0,maxval=10,dtype=tf.int32)
print(A)


tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 2 2], shape=(3,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor(
[[8 2 6]
 [3 5 7]
 [2 0 8]], shape=(3, 3), dtype=int32)
tf.Tensor([8 2 6], shape=(3,), dtype=int32)


In [51]:
print(A[0])
print(A[0:2])
print(A[0:2])

tf.Tensor([8 2 6], shape=(3,), dtype=int32)
tf.Tensor(
[[8 2 6]
 [3 5 7]], shape=(2, 3), dtype=int32)


In [53]:
#reshaping
x=tf.range(9)
print(x)
x=tf.reshape(x,(3,3))
print(x)

print(tf.transpose(x))

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
